effect = {"": "",
          "4": "Community Sparkle",
          "5": "Holy Glow",
          "6": "Green Confetti",
          "7": "Purple Confetti",
          "8": "Haunted Ghosts",
          "9": "Green Energy",
          "10": "Purple Energy",
          "11": "Circling TF Logo",
          "12": "Massed Flies",
          "13": "Burning Flames",
          "14": "Scorching Flames",
          "15": "Searing Plasma",
          "16": "Vivid Plasma",
          "17": "Sunbeams",
          "18": "Circling Peace Sign",
          "19": "Circling Heart",
          "20": "Map Stamps",
          "29": "Stormy Storm",
          "30": "Blizzardy Storm",
          "31": "Nuts n' Bolts",
          "32": "Orbiting Planets",
          "33": "Orbiting Fire",
          "34": "Bubbling",
          "35": "Smoking",
          "36": "Steaming",
          "37": "Flaming Lantern",
          "38": "Cloudy Moon",
          "39": "Cauldron Bubbles",
          "40": "Eerie Orbiting Fire",
          "43": "Knifestorm",
          "44": "Misty Skull",
          "45": "Harvest Moon",
          "46": "It's A Secret To Everybody",
          "47": "Stormy 13th Hour",
          "56": "Kill-a-Watt",
          "57": "Terror-Watt",
          "58": "Cloud 9",
          "59": "Aces High",
          "60": "Dead Presidents",
          "61": "Miami Nights",
          "62": "Disco Beat Down",
          "63": "Phosphorous",
          "64": "Sulphurous",
          "65": "Memory Leak",
          "66": "Overclocked",
          "67": "Electrostatic",
          "68": "Power Surge",
          "69": "Anti-Freeze",
          "70": "Time Warp",
          "71": "Green Black Hole",
          "72": "Roboactive",
          "73": "Arcana",
          "74": "Spellbound",
          "75": "Chiroptera Venenata",
          "76": "Poisoned Shadows",
          "77": "Something Burning This Way Comes",
          "78": "Hellfire",
          "79": "Darkblaze",
          "80": "Demonflame",
          "81": "Bonzo The All-Gnawing",
          "82": "Amaranthine",
          "83": "Stare From Beyond",
          "84": "The Ooze",
          "85": "Ghastly Ghosts Jr",
          "86": "Haunted Phantasm Jr",
          "87": "Frostbite",
          "88": "Molten Mallard",
          "89": "Morning Glory",
          "90": "Death at Dusk",
          "91": "Abduction",
          "92": "Atomic",
          "93": "Subatomic",
          "94": "Electric Hat Protector",
          "95": "Magnetic Hat Protector",
          "96": "Voltaic Hat Protector",
          "97": "Galactic Codex",
          "98": "Ancient Codex",
          "99": "Nebula",
          "100": "Death by Disco",
          "101": "It's a mystery to everyone",
          "102": "It's a puzzle to me",
          "103": "Ether Trail",
          "104": "Nether Trail",
          "105": "Ancient Eldritch",
          "106": "Eldritch Flame",
          "107": "Neutron Star",
          "108": "Tesla Coil",
          "109": "Starstorm Insomnia",
          "110": "Starstorm Slumber",
          "111": "Brain Drain",
          "112": "Open Mind",
          "113": "Head of Steam",
          "114": "Galactic Gateway",
          "115": "The Eldritch Opening",
          "116": "The Dark Doorway",
          "117": "Ring of Fire",
          "118": "Vicious Circle",
          "119": "White Lightning",
          "120": "Omniscient Orb",
          "121": "Clairvoyance",
          "122": "Fifth Dimension",
          "123": "Vicious Vortex",
          "124": "Menacing Miasma",
          "125": "Abyssal Aura",
          "126": "Wicked Wood",
          "127": "Ghastly Grove",
          "128": "Mystical Medley",
          "129": "Ethereal Essence",
          "130": "Twisted Radiance",
          "131": "Violet Vortex",
          "132": "Verdant Vortex",
          "133": "Valiant Vortex",
          "134": "Sparkling Lights",
          "135": "Frozen Icefall",
          "136": "Fragmented Gluons",
          "137": "Fragmented Quarks",
          "138": "Fragmented Photons",
          "139": "Defragmenting Reality",
          "141": "Fragmenting Reality",
          "142": "Refragmenting Reality",
          "143": "Snowfallen",
          "144": "Snowblinded",
          "145": "Pyroland Daydream",
          "147": "Verdatica",
          "148": "Aromatica",
          "149": "Chromatica",
          "150": "Prismatica",
          "151": "Bee Swarm",
          "152": "Frisky Fireflies",
          "153": "Smoldering Spirits",
          "154": "Wandering Wisps",
          "155": "Kaleidoscope",
          "156": "Green Giggler",
          "157": "Laugh-O-Lantern",
          "158": "Plum Prankster",
          "159": "Pyroland Nightmare",
          "160": "Gravelly Ghoul",
          "161": "Vexed Volcanics",
          "162": "Gourdian Angel",
          "163": "Pumpkin Party",
          "164": "Frozen Fractals",
          "165": "Lavender Landfall",
          "166": "Special Snowfall",
          "167": "Divine Desire",
          "168": "Distant Dream",
          "169": "Violent Wintertide",
          "170": "Blighted Snowstorm",
          "171": "Pale Nimbus",
          "172": "Genus Plasmos",
          "173": "Serenus Lumen",
          "174": "Ventum Maris",
          "175": "Mirthful Mistletoe",
          "701": "Hot",
          "702": "Isotope",
          "703": "Cool",
          "704": "Energy Orb",
          "3001": "Showstopper",
          "3002": "Showstopper",
          "3003": "Holy Grail",
          "3004": "'72",
          "3005": "Fountain of Delight",
          "3006": "Screaming Tiger",
          "3007": "Skill Gotten Gains",
          "3008": "Midnight Whirlwind",
          "3009": "Silver Cyclone",
          "3010": "Mega Strike",
          "3011": "Haunted Phantasm",
          "3012": "Ghastly Ghosts",
          "3013": "Hellish Inferno",
          "3014": "Spectral Swirl",
          "3015": "Infernal Flames",
          "3016": "Infernal Smoke",
          "3017": "Acidic Bubbles of Envy",
          "3018": "Flammable Bubbles of Attraction",
          "3019": "Poisonous Bubbles of Regret",
          "3020": "Roaring Rockets",
          "3021": "Spooky Night",
          "3022": "Ominous Night",
          "3023": "Bewitched",
          "3024": "Accursed",
          "3025": "Enchanted",
          "3026": "Static Mist",
          "3027": "Eerie Lightning",
          "3028": "Terrifying Thunder",
          "3029": "Jarate Shock",
          "3030": "Nether Void",
          "3031": "Good-Hearted Goodies",
          "3032": "Wintery Wisp",
          "3033": "Arctic Aurora",
          "3034": "Winter Spirit",
          "3035": "Festive Spirit",
          "3036": "Magical Spirit",
          "3037": "Spectral Escort",
          "3038": "Astral Presence",
          "3039": "Arcane Assistance",
          "3040": "Arcane Assistance",
          "3041": "Emerald Allurement",
          "3042": "Pyrophoric Personality",
          "3043": "Spellbound Aspect",
          "3044": "Static Shock",
          "3045": "Veno Shock",
          "3046": "Toxic Terrors",
          "3047": "Arachnid Assault",
          "3048": "Creepy Crawlies",
          "3049": "Delightful Star",
          "3050": "Frosted Star",
          "3051": "Apotheosis",
          "3052": "Ascension",
          "3053": "Reindoonicorn Rancher",
          "3054": "Reindoonicorn Rancher",
          "3055": "Twinkling Lights",
          "3056": "Shimmering Lights",

          }
